# Generated by Django 4.0.4 on 2022-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('instituted', models.CharField(max_length=50)),
                ('assigement1', models.CharField(max_length=50)),
                ('assigement2', models.CharField(max_length=50)),
                ('assigentnt3', models.CharField(max_length=50)),
            ],
        ),
    ]
