# Generated by Django 4.0.4 on 2022-08-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='assigement1',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='assigement2',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='instituted',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='assigentnt3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
    ]
