# Generated by Django 4.0.4 on 2022-08-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0002_remove_studentdata_assigement1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='assigentnt3',
        ),
    ]
