# Generated by Django 4.0.4 on 2022-08-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0004_rename_first_name_studentdata_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='Data',
            new_name='first_name',
        ),
    ]
