# Generated by Django 4.0.6 on 2022-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0005_rename_data_studentdata_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mobile',
            field=models.CharField(max_length=150),
        ),
    ]
