# Generated by Django 4.0.6 on 2022-08-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0006_alter_studentdata_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='mobile',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='first_name',
            new_name='task',
        ),
    ]
